import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.transactions': 'Transactions',
    'nav.merchants': 'Merchants',
    'nav.operators': 'Operators',
    'nav.giftCards': 'Gift Cards',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'topbar.search': 'Search transactions, merchants...',
    'topbar.notifications': 'Notifications',
    'topbar.profile': 'Profile',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Real-time overview of the Cadoobi payment ecosystem.',
    'dashboard.today': 'Today',
    'dashboard.totalPayments': 'Total Payments Today',
    'dashboard.activeMerchants': 'Active Merchants',
    'dashboard.pendingTransactions': 'Pending Transactions',
    'dashboard.totalRevenue': 'Total Revenue Today',
    'dashboard.paymentTrends': 'Payment Trends',
    'dashboard.trendsSubtitle': 'Transaction volume per hour',
    'dashboard.daily': 'Daily',
    'dashboard.weekly': 'Weekly',
    'dashboard.monthly': 'Monthly',
    'dashboard.operatorShare': 'Operator Share',
    'dashboard.marketDistribution': 'Current market distribution',
    'dashboard.capacity': 'Capacity',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.viewAll': 'View All',
    'dashboard.table.reference': 'Reference',
    'dashboard.table.merchant': 'Merchant',
    'dashboard.table.amount': 'Amount (XOF)',
    'dashboard.table.operator': 'Operator',
    'dashboard.table.status': 'Status',
    'dashboard.table.timestamp': 'Timestamp',
    'dashboard.quickActions.initiatePayment': 'Initiate New Payment',
    'dashboard.quickActions.initiatePaymentDesc': 'Send money to any operator wallet',
    'dashboard.quickActions.addMerchant': 'Add Merchant',
    'dashboard.quickActions.addMerchantDesc': 'Register a new business partner',
    'dashboard.quickActions.generateReport': 'Generate Report',
    'dashboard.quickActions.generateReportDesc': 'Export data for audit and review',
    'transactions.title': 'Payments Ledger',
    'transactions.subtitle': 'Manage and monitor all XOF transactions across the network.',
    'transactions.export': 'Export CSV',
    'transactions.initiate': 'Initiate New Payment',
    'transactions.filter.status': 'Transaction Status',
    'transactions.filter.allStatus': 'All Statuses',
    'transactions.filter.dateRange': 'Date Range',
    'transactions.filter.today': 'Today',
    'transactions.filter.yesterday': 'Yesterday',
    'transactions.filter.custom': 'Custom',
    'transactions.filter.merchant': 'Merchant Name',
    'transactions.filter.searchMerchant': 'Search merchant...',
    'transactions.filter.operator': 'Operator',
    'transactions.filter.allOperators': 'All Operators',
    'transactions.filter.reset': 'Reset Filters',
    'transactions.filter.title': 'Filters',
    'transactions.table.ref': 'Payment Ref',
    'transactions.table.merchant': 'Merchant',
    'transactions.table.phone': 'Customer Phone',
    'transactions.table.amount': 'Amount (XOF)',
    'transactions.table.operator': 'Operator',
    'transactions.table.status': 'Status',
    'transactions.table.date': 'Date/Time',
    'transactions.table.actions': 'Actions',
    'transactions.pagination.showing': 'Showing',
    'transactions.pagination.of': 'of',
    'transactions.pagination.transactions': 'transactions',
    'merchants.title': 'Merchants Directory',
    'merchants.subtitle': 'Manage business partners and their platform access.',
    'merchants.register': 'Register Merchant',
    'merchants.stats.active': 'Active Merchants',
    'merchants.stats.pending': 'Pending Review',
    'merchants.stats.blocked': 'Blocked/Suspended',
    'merchants.filter.search': 'Search by name, ID or location...',
    'merchants.filter.allCategories': 'All Categories',
    'merchants.filter.retail': 'Retail',
    'merchants.filter.healthcare': 'Healthcare',
    'merchants.filter.logistics': 'Logistics',
    'merchants.card.joined': 'Joined',
    'merchants.card.volume': 'Vol.',
    'merchants.card.viewProfile': 'View Profile',
    'operators.title': 'Network Operators',
    'operators.subtitle': 'Real-time gateway status and performance monitoring.',
    'operators.health': 'System Health',
    'operators.config': 'Gateway Config',
    'operators.card.gateway': 'Gateway',
    'operators.card.successRate': 'Success Rate',
    'operators.card.latency': 'Latency',
    'operators.load.title': 'Network Load',
    'operators.load.desc': 'System is performing within optimal parameters. No critical outages detected in the last 24 hours.',
    'operators.load.logs': 'View Incident Logs',
    'operators.metrics.title': 'Performance Metrics (Last 60m)',
    'operators.metrics.avgResponse': 'Avg. Response Time',
    'operators.metrics.apiCalls': 'Total API Calls',
    'operators.metrics.errorRate': 'Error Rate',
    'operators.metrics.activeNodes': 'Active Nodes',
    'operators.metrics.stable': 'Stable',
    'operators.metrics.ago': 'ago',
    'operators.metrics.now': 'Now',
    'giftcards.title': 'Gift Cards & Rewards',
    'giftcards.subtitle': 'Issue, track and manage digital and physical value cards.',
    'giftcards.issue': 'Issue New Card',
    'giftcards.stats.totalIssued': 'Total Issued',
    'giftcards.stats.redemptionRate': 'Redemption Rate',
    'giftcards.stats.pendingActivation': 'Pending Activation',
    'giftcards.stats.expiredValue': 'Expired Value',
    'giftcards.stats.issuedDesc': '+12% from last month',
    'giftcards.stats.redemptionDesc': 'Optimal range',
    'giftcards.stats.pendingDesc': 'Awaiting merchant sync',
    'giftcards.stats.expiredDesc': 'Reclaimed to treasury',
    'giftcards.search.placeholder': 'Search by card ID or merchant...',
    'giftcards.table.cardId': 'Card ID',
    'giftcards.table.merchant': 'Merchant',
    'giftcards.table.value': 'Value',
    'giftcards.table.status': 'Status',
    'giftcards.table.expiry': 'Expiry',
    'giftcards.table.actions': 'Actions',
    'giftcards.history': 'View All Redemption History',
    'users.title': 'Users & Access Control',
    'users.subtitle': 'Manage administrative access and role-based permissions.',
    'users.invite': 'Invite Team Member',
    'users.stats.totalTeam': 'Total Team Members',
    'users.stats.security': 'Security Compliance',
    'users.stats.activeSessions': 'Active Sessions',
    'users.stats.newThisWeek': '+2 this week',
    'users.stats.rolesDefined': '4 Roles Defined',
    'users.stats.failedLogins': '2 Failed Logins',
    'users.search.placeholder': 'Search by name, email or role...',
    'users.filter.allRoles': 'All Roles',
    'users.table.user': 'User',
    'users.table.role': 'Role',
    'users.table.status': 'Status',
    'users.table.lastActive': 'Last Active',
    'users.table.actions': 'Actions',
    'users.rbac.title': 'Role-Based Access Control (RBAC)',
    'users.rbac.desc': 'All administrative actions are logged and auditable. Multi-factor authentication is enforced for all Super Admin accounts.',
    'users.modal.inviteTitle': 'Invite Team Member',
    'users.modal.inviteSubtitle': 'Grant access to the Cadoobi administration panel.',
    'users.modal.fullName': 'Full Name',
    'users.modal.fullNamePlaceholder': 'e.g. Amadou Thiam',
    'users.modal.email': 'Email Address',
    'users.modal.emailPlaceholder': 'amadou@example.com',
    'users.modal.assignRole': 'Assign Role',
    'users.modal.roleAdmin': 'Admin (Full Control)',
    'users.modal.roleCompliance': 'Compliance Officer',
    'users.modal.roleFinance': 'Finance Manager',
    'users.modal.roleSupport': 'Support Agent',
    'users.modal.sendEmail': 'Send welcome email',
    'users.modal.sendEmailDesc': 'User will receive login instructions',
    'users.modal.sendInvitation': 'Send Invitation',
    'users.modal.cancel': 'Cancel',
    'merchants.modal.registerTitle': 'Register Merchant',
    'merchants.modal.registerSubtitle': 'Complete the business profile to begin onboarding',
    'merchants.modal.step1': 'Basic Info',
    'merchants.modal.step2': 'Settlement Accounts',
    'merchants.modal.businessName': 'Business Name',
    'merchants.modal.businessNamePlaceholder': 'e.g. SeneFood Group',
    'merchants.modal.merchantCode': 'Merchant Code',
    'merchants.modal.merchantCodePlaceholder': 'M-XXXXX',
    'merchants.modal.contactPerson': 'Contact Person',
    'merchants.modal.contactPersonPlaceholder': 'Full Name',
    'merchants.modal.phone': 'Phone Number',
    'merchants.modal.email': 'Email Address',
    'merchants.modal.address': 'Physical Address',
    'merchants.modal.addressPlaceholder': 'Street name, City, Region',
    'merchants.modal.settlementDetails': 'Step 2: Settlement Details',
    'merchants.modal.settlementType': 'Settlement Type',
    'merchants.modal.bankAccount': 'Bank Account',
    'merchants.modal.mobileMoney': 'Mobile Money',
    'merchants.modal.register': 'Register Merchant',
    'profile.title': 'User Profile',
    'profile.subtitle': 'Manage your identity, security credentials, and application preferences.',
    'profile.verified': 'Verified',
    'profile.password.title': 'Password',
    'profile.password.desc': 'Last changed 45 days ago. We recommend updating it every 90 days.',
    'profile.password.button': 'Change Password',
    'profile.2fa.title': 'Two-Factor Auth',
    'profile.2fa.desc': 'Add an extra layer of security to your account via SMS or Authenticator app.',
    'profile.2fa.button': 'Manage 2FA Settings',
    'profile.preferences.title': 'Preferences',
    'profile.preferences.language': 'Language',
    'profile.preferences.timezone': 'Timezone',
    'profile.preferences.displayMode': 'Display Mode',
    'profile.preferences.light': 'Light',
    'profile.preferences.dark': 'Dark',
    'profile.preferences.signOut': 'Sign Out of All Devices',
    'profile.health.title': 'Account Health',
    'profile.health.score': 'Secure Score',
    'profile.health.desc': 'Your account uses all recommended security features. Good job, Amadou!',
    'reports.title': 'Analytics & Reports',
    'reports.subtitle': 'Deep insights into platform performance and financial health.',
    'reports.share': 'Share Report',
    'reports.export': 'Export PDF',
    'reports.filter.daily': 'Daily',
    'reports.filter.weekly': 'Weekly',
    'reports.filter.monthly': 'Monthly',
    'reports.filter.quarterly': 'Quarterly',
    'reports.filter.more': 'More Filters',
    'reports.revenue.title': 'Revenue Growth',
    'reports.revenue.desc': 'Total platform throughput over time.',
    'reports.operator.title': 'Operator Share',
    'reports.operator.desc': 'Market distribution by transaction count.',
    'reports.scheduled.title': 'Scheduled Reports',
    'reports.scheduled.monthly': 'Monthly Settlement',
    'reports.scheduled.merchant': 'Merchant Performance',
    'reports.scheduled.next': 'Next',
    'reports.scheduled.everyMonday': 'Every Monday',
    'reports.insights.title': 'Automated Insights',
    'reports.insights.desc': 'Our AI engine has detected a 15% increase in transaction volume from the Almadies region. Consider expanding merchant onboarding in this area.',
    'reports.insights.read': 'Read Full Analysis',
    'settings.title': 'Platform Settings',
    'settings.subtitle': 'Configure your Cadoobi platform environment, security protocols, and integration endpoints.',
    'settings.nav.navigation': 'Navigation',
    'settings.nav.branding': 'General Branding',
    'settings.nav.access': 'Access Control',
    'settings.nav.security': 'Security Policy',
    'settings.nav.communication': 'Communication',
    'settings.nav.email': 'Email Notifications',
    'settings.nav.developer': 'Developer',
    'settings.nav.api': 'API Integration',
    'settings.branding.title': 'General Branding',
    'settings.branding.desc': 'Public identity and regional formatting for the platform.',
    'settings.branding.name': 'Platform Name',
    'settings.branding.nameDesc': 'The name displayed in customer emails and receipts.',
    'settings.branding.currency': 'Primary Currency',
    'settings.branding.currency.xof': 'West African CFA franc (XOF)',
    'settings.branding.currency.xaf': 'Central African CFA franc (XAF)',
    'settings.branding.currency.eur': 'Euro (EUR)',
    'settings.branding.currency.usd': 'US Dollar (USD)',
    'settings.branding.timezone': 'Timezone',
    'settings.branding.timezone.dakar': '(GMT+00:00) Dakar, Senegal',
    'settings.branding.timezone.abidjan': '(GMT+00:00) Abidjan, Côte d\'Ivoire',
    'settings.branding.timezone.lagos': '(GMT+01:00) Lagos, Nigeria',
    'settings.branding.save': 'Save General Settings',
    'settings.security.title': 'Security Policy',
    'settings.security.desc': 'Manage authentication strictness and session lifecycle.',
    'settings.security.2fa': 'Two-Factor Auth',
    'settings.security.2faDesc': 'Mandatory for all admin roles',
    'settings.security.ip': 'IP Whitelisting',
    'settings.security.ipDesc': 'Restrict access by location',
    'settings.security.minPass': 'Min Password Length',
    'settings.security.timeout': 'Session Timeout (min)',
    'settings.security.save': 'Apply Security Updates',
    'settings.api.title': 'API Integration',
    'settings.api.desc': 'Connect third-party services and manage webhooks.',
    'settings.api.prodKey': 'Production API Key',
    'settings.api.reveal': 'Reveal Key',
    'settings.api.webhook': 'Webhook URL',
    'settings.api.webhookDesc': 'We\'ll send POST requests for all completed transaction events to this endpoint.',
    'settings.api.save': 'Save Integration',
    'common.active': 'Active',
    'common.pending': 'Pending',
    'common.blocked': 'Blocked',
    'common.failed': 'Failed',
    'common.success': 'Success',
    'common.next': 'Next Step',
    'common.back': 'Back',
    'common.edit': 'Edit',
    'common.cancel': 'Cancel',
    'common.digital': 'Digital',
    'common.physical': 'Physical',
    'common.redeemed': 'Redeemed',
    'common.expired': 'Expired',
    'common.healthy': 'Healthy',
    'common.degraded': 'Degraded',
    'common.operator.orange': 'Orange Money',
    'common.operator.wave': 'Wave',
    'common.operator.free': 'Free Money',
    'common.operator.emoney': 'E-Money',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.transactions': 'Transactions',
    'nav.merchants': 'Marchands',
    'nav.operators': 'Opérateurs',
    'nav.giftCards': 'Cartes Cadeaux',
    'nav.users': 'Utilisateurs',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',
    'topbar.search': 'Rechercher des transactions, marchands...',
    'topbar.notifications': 'Notifications',
    'topbar.profile': 'Profil',
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Aperçu en temps réel de l\'écosystème de paiement Cadoobi.',
    'dashboard.today': 'Aujourd\'hui',
    'dashboard.totalPayments': 'Total des Paiements Aujourd\'hui',
    'dashboard.activeMerchants': 'Marchands Actifs',
    'dashboard.pendingTransactions': 'Transactions en Attente',
    'dashboard.totalRevenue': 'Revenu Total Aujourd\'hui',
    'dashboard.paymentTrends': 'Tendances de Paiement',
    'dashboard.trendsSubtitle': 'Volume de transactions par heure',
    'dashboard.daily': 'Quotidien',
    'dashboard.weekly': 'Hebdomadaire',
    'dashboard.monthly': 'Mensuel',
    'dashboard.operatorShare': 'Part des Opérateurs',
    'dashboard.marketDistribution': 'Distribution actuelle du marché',
    'dashboard.capacity': 'Capacité',
    'dashboard.recentTransactions': 'Transactions Récentes',
    'dashboard.viewAll': 'Voir Tout',
    'dashboard.table.reference': 'Référence',
    'dashboard.table.merchant': 'Marchand',
    'dashboard.table.amount': 'Montant (XOF)',
    'dashboard.table.operator': 'Opérateur',
    'dashboard.table.status': 'Statut',
    'dashboard.table.timestamp': 'Horodatage',
    'dashboard.quickActions.initiatePayment': 'Initier un Nouveau Paiement',
    'dashboard.quickActions.initiatePaymentDesc': 'Envoyer de l\'argent vers n\'importe quel portefeuille d\'opérateur',
    'dashboard.quickActions.addMerchant': 'Ajouter un Marchand',
    'dashboard.quickActions.addMerchantDesc': 'Enregistrer un nouveau partenaire commercial',
    'dashboard.quickActions.generateReport': 'Générer un Rapport',
    'dashboard.quickActions.generateReportDesc': 'Exporter les données pour audit et révision',
    'transactions.title': 'Registre des Paiements',
    'transactions.subtitle': 'Gérer et surveiller toutes les transactions XOF sur le réseau.',
    'transactions.export': 'Exporter CSV',
    'transactions.initiate': 'Initier un Nouveau Paiement',
    'transactions.filter.status': 'Statut de la Transaction',
    'transactions.filter.allStatus': 'Tous les Statuts',
    'transactions.filter.dateRange': 'Période',
    'transactions.filter.today': 'Aujourd\'hui',
    'transactions.filter.yesterday': 'Hier',
    'transactions.filter.custom': 'Personnalisé',
    'transactions.filter.merchant': 'Nom du Marchand',
    'transactions.filter.searchMerchant': 'Rechercher un marchand...',
    'transactions.filter.operator': 'Opérateur',
    'transactions.filter.allOperators': 'Tous les Opérateurs',
    'transactions.filter.reset': 'Réinitialiser les Filtres',
    'transactions.filter.title': 'Filtres',
    'transactions.table.ref': 'Réf. de Paiement',
    'transactions.table.merchant': 'Marchand',
    'transactions.table.phone': 'Téléphone Client',
    'transactions.table.amount': 'Montant (XOF)',
    'transactions.table.operator': 'Opérateur',
    'transactions.table.status': 'Statut',
    'transactions.table.date': 'Date/Heure',
    'transactions.table.actions': 'Actions',
    'transactions.pagination.showing': 'Affichage de',
    'transactions.pagination.of': 'sur',
    'transactions.pagination.transactions': 'transactions',
    'merchants.title': 'Répertoire des Marchands',
    'merchants.subtitle': 'Gérer les partenaires commerciaux et leur accès à la plateforme.',
    'merchants.register': 'Enregistrer un Marchand',
    'merchants.stats.active': 'Marchands Actifs',
    'merchants.stats.pending': 'En Attente de Révision',
    'merchants.stats.blocked': 'Bloqués/Suspendus',
    'merchants.filter.search': 'Rechercher par nom, ID ou lieu...',
    'merchants.filter.allCategories': 'Toutes les Catégories',
    'merchants.filter.retail': 'Commerce de détail',
    'merchants.filter.healthcare': 'Santé',
    'merchants.filter.logistics': 'Logistique',
    'merchants.card.joined': 'Inscrit le',
    'merchants.card.volume': 'Vol.',
    'merchants.card.viewProfile': 'Voir le Profil',
    'operators.title': 'Opérateurs Réseau',
    'operators.subtitle': 'Statut de la passerelle en temps réel et surveillance des performances.',
    'operators.health': 'Santé du Système',
    'operators.config': 'Config. de la Passerelle',
    'operators.card.gateway': 'Passerelle',
    'operators.card.successRate': 'Taux de Réussite',
    'operators.card.latency': 'Latence',
    'operators.load.title': 'Charge du Réseau',
    'operators.load.desc': 'Le système fonctionne selon des paramètres optimaux. Aucune panne critique détectée au cours des dernières 24 heures.',
    'operators.load.logs': 'Voir les Journaux d\'Incidents',
    'operators.metrics.title': 'Mesures de Performance (Dernières 60m)',
    'operators.metrics.avgResponse': 'Temps de Réponse Moyen',
    'operators.metrics.apiCalls': 'Total des Appels API',
    'operators.metrics.errorRate': 'Taux d\'Erreur',
    'operators.metrics.activeNodes': 'Nœuds Actifs',
    'operators.metrics.stable': 'Stable',
    'operators.metrics.ago': 'il y a',
    'operators.metrics.now': 'Maintenant',
    'giftcards.title': 'Cartes Cadeaux & Récompenses',
    'giftcards.subtitle': 'Émettez, suivez et gérez les cartes de valeur numériques et physiques.',
    'giftcards.issue': 'Émettre une Nouvelle Carte',
    'giftcards.stats.totalIssued': 'Total Émis',
    'giftcards.stats.redemptionRate': 'Taux d\'Utilisation',
    'giftcards.stats.pendingActivation': 'En Attente d\'Activation',
    'giftcards.stats.expiredValue': 'Valeur Expirée',
    'giftcards.stats.issuedDesc': '+12% par rapport au mois dernier',
    'giftcards.stats.redemptionDesc': 'Plage optimale',
    'giftcards.stats.pendingDesc': 'En attente de synchronisation marchand',
    'giftcards.stats.expiredDesc': 'Récupéré par la trésorerie',
    'giftcards.search.placeholder': 'Rechercher par ID de carte ou marchand...',
    'giftcards.table.cardId': 'ID de Carte',
    'giftcards.table.merchant': 'Marchand',
    'giftcards.table.value': 'Valeur',
    'giftcards.table.status': 'Statut',
    'giftcards.table.expiry': 'Expiration',
    'giftcards.table.actions': 'Actions',
    'giftcards.history': 'Voir tout l\'historique d\'utilisation',
    'users.title': 'Utilisateurs & Contrôle d\'Accès',
    'users.subtitle': 'Gérez l\'accès administratif et les autorisations basées sur les rôles.',
    'users.invite': 'Inviter un Membre de l\'Équipe',
    'users.stats.totalTeam': 'Total des Membres de l\'Équipe',
    'users.stats.security': 'Conformité de Sécurité',
    'users.stats.activeSessions': 'Sessions Actives',
    'users.stats.newThisWeek': '+2 cette semaine',
    'users.stats.rolesDefined': '4 Rôles Définis',
    'users.stats.failedLogins': '2 Échecs de Connexion',
    'users.search.placeholder': 'Rechercher par nom, email ou rôle...',
    'users.filter.allRoles': 'Tous les Rôles',
    'users.table.user': 'Utilisateur',
    'users.table.role': 'Rôle',
    'users.table.status': 'Statut',
    'users.table.lastActive': 'Dernière Activité',
    'users.table.actions': 'Actions',
    'users.rbac.title': 'Contrôle d\'Accès Basé sur les Rôles (RBAC)',
    'users.rbac.desc': 'Toutes les actions administratives sont enregistrées et auditables. L\'authentification multi-facteurs est appliquée pour tous les comptes Super Admin.',
    'users.modal.inviteTitle': 'Inviter un membre de l\'équipe',
    'users.modal.inviteSubtitle': 'Accorder l\'accès au panneau d\'administration Cadoobi.',
    'users.modal.fullName': 'Nom complet',
    'users.modal.fullNamePlaceholder': 'ex: Amadou Thiam',
    'users.modal.email': 'Adresse e-mail',
    'users.modal.emailPlaceholder': 'amadou@exemple.com',
    'users.modal.assignRole': 'Attribuer un rôle',
    'users.modal.roleAdmin': 'Admin (Contrôle total)',
    'users.modal.roleCompliance': 'Agent de conformité',
    'users.modal.roleFinance': 'Responsable financier',
    'users.modal.roleSupport': 'Agent de support',
    'users.modal.sendEmail': 'Envoyer un e-mail de bienvenue',
    'users.modal.sendEmailDesc': 'L\'utilisateur recevra des instructions de connexion',
    'users.modal.sendInvitation': 'Envoyer l\'invitation',
    'users.modal.cancel': 'Annuler',
    'merchants.modal.registerTitle': 'Enregistrer un marchand',
    'merchants.modal.registerSubtitle': 'Complétez le profil de l\'entreprise pour commencer l\'intégration',
    'merchants.modal.step1': 'Infos de base',
    'merchants.modal.step2': 'Comptes de règlement',
    'merchants.modal.businessName': 'Nom de l\'entreprise',
    'merchants.modal.businessNamePlaceholder': 'ex: Groupe SeneFood',
    'merchants.modal.merchantCode': 'Code marchand',
    'merchants.modal.merchantCodePlaceholder': 'M-XXXXX',
    'merchants.modal.contactPerson': 'Personne de contact',
    'merchants.modal.contactPersonPlaceholder': 'Nom complet',
    'merchants.modal.phone': 'Numéro de téléphone',
    'merchants.modal.email': 'Adresse e-mail',
    'merchants.modal.address': 'Adresse physique',
    'merchants.modal.addressPlaceholder': 'Nom de rue, Ville, Région',
    'merchants.modal.settlementDetails': 'Étape 2 : Détails du règlement',
    'merchants.modal.settlementType': 'Type de règlement',
    'merchants.modal.bankAccount': 'Compte bancaire',
    'merchants.modal.mobileMoney': 'Mobile Money',
    'merchants.modal.register': 'Enregistrer le marchand',
    'profile.title': 'Profil de l\'utilisateur',
    'profile.subtitle': 'Gérez votre identité, vos identifiants de sécurité et vos préférences d\'application.',
    'profile.verified': 'Vérifié',
    'profile.password.title': 'Mot de passe',
    'profile.password.desc': 'Dernière modification il y a 45 jours. Nous vous recommandons de le mettre à jour tous les 90 jours.',
    'profile.password.button': 'Modifier le mot de passe',
    'profile.2fa.title': 'Authentification à deux facteurs',
    'profile.2fa.desc': 'Ajoutez une couche de sécurité supplémentaire à votre compte via SMS ou application d\'authentification.',
    'profile.2fa.button': 'Gérer les paramètres 2FA',
    'profile.preferences.title': 'Préférences',
    'profile.preferences.language': 'Langue',
    'profile.preferences.timezone': 'Fuseau horaire',
    'profile.preferences.displayMode': 'Mode d\'affichage',
    'profile.preferences.light': 'Clair',
    'profile.preferences.dark': 'Sombre',
    'profile.preferences.signOut': 'Se déconnecter de tous les appareils',
    'profile.health.title': 'Santé du compte',
    'profile.health.score': 'Score de sécurité',
    'profile.health.desc': 'Votre compte utilise toutes les fonctionnalités de sécurité recommandées. Bon travail, Amadou !',
    'reports.title': 'Analyses & Rapports',
    'reports.subtitle': 'Aperçu approfondi des performances de la plateforme et de la santé financière.',
    'reports.share': 'Partager le Rapport',
    'reports.export': 'Exporter en PDF',
    'reports.filter.daily': 'Quotidien',
    'reports.filter.weekly': 'Hebdomadaire',
    'reports.filter.monthly': 'Mensuel',
    'reports.filter.quarterly': 'Trimestriel',
    'reports.filter.more': 'Plus de Filtres',
    'reports.revenue.title': 'Croissance des Revenus',
    'reports.revenue.desc': 'Débit total de la plateforme au fil du temps.',
    'reports.operator.title': 'Part des Opérateurs',
    'reports.operator.desc': 'Répartition du marché par nombre de transactions.',
    'reports.scheduled.title': 'Rapports Planifiés',
    'reports.scheduled.monthly': 'Règlement Mensuel',
    'reports.scheduled.merchant': 'Performance Marchand',
    'reports.scheduled.next': 'Suivant',
    'reports.scheduled.everyMonday': 'Chaque Lundi',
    'reports.insights.title': 'Analyses Automatisées',
    'reports.insights.desc': 'Notre moteur d\'IA a détecté une augmentation de 15 % du volume de transactions dans la région des Almadies. Envisagez d\'étendre l\'intégration des marchands dans cette zone.',
    'reports.insights.read': 'Lire l\'Analyse Complète',
    'settings.title': 'Paramètres de la Plateforme',
    'settings.subtitle': 'Configurez l\'environnement de votre plateforme Cadoobi, les protocoles de sécurité et les points de terminaison d\'intégration.',
    'settings.nav.navigation': 'Navigation',
    'settings.nav.branding': 'Image de Marque',
    'settings.nav.access': 'Contrôle d\'Accès',
    'settings.nav.security': 'Politique de Sécurité',
    'settings.nav.communication': 'Communication',
    'settings.nav.email': 'Notifications par Email',
    'settings.nav.developer': 'Développeur',
    'settings.nav.api': 'Intégration API',
    'settings.branding.title': 'Image de Marque Générale',
    'settings.branding.desc': 'Identité publique et formatage régional pour la plateforme.',
    'settings.branding.name': 'Nom de la Plateforme',
    'settings.branding.nameDesc': 'Le nom affiché dans les e-mails et les reçus des clients.',
    'settings.branding.currency': 'Devise Principale',
    'settings.branding.currency.xof': 'Franc CFA d\'Afrique de l\'Ouest (XOF)',
    'settings.branding.currency.xaf': 'Franc CFA d\'Afrique Centrale (XAF)',
    'settings.branding.currency.eur': 'Euro (EUR)',
    'settings.branding.currency.usd': 'Dollar US (USD)',
    'settings.branding.timezone': 'Fuseau Horaire',
    'settings.branding.timezone.dakar': '(GMT+00:00) Dakar, Sénégal',
    'settings.branding.timezone.abidjan': '(GMT+00:00) Abidjan, Côte d\'Ivoire',
    'settings.branding.timezone.lagos': '(GMT+01:00) Lagos, Nigéria',
    'settings.branding.save': 'Enregistrer les Paramètres Généraux',
    'settings.security.title': 'Politique de Sécurité',
    'settings.security.desc': 'Gérez la rigueur de l\'authentification et le cycle de vie des sessions.',
    'settings.security.2fa': 'Authentification à Deux Facteurs',
    'settings.security.2faDesc': 'Obligatoire pour tous les rôles d\'administrateur',
    'settings.security.ip': 'Liste Blanche d\'IP',
    'settings.security.ipDesc': 'Restreindre l\'accès par emplacement',
    'settings.security.minPass': 'Longueur Minimale du Mot de Passe',
    'settings.security.timeout': 'Délai d\'Expiration de la Session (min)',
    'settings.security.save': 'Appliquer les Mises à Jour de Sécurité',
    'settings.api.title': 'Intégration API',
    'settings.api.desc': 'Connectez des services tiers et gérez les webhooks.',
    'settings.api.prodKey': 'Clé API de Production',
    'settings.api.reveal': 'Révéler la Clé',
    'settings.api.webhook': 'URL du Webhook',
    'settings.api.webhookDesc': 'Nous enverrons des requêtes POST pour tous les événements de transaction terminés à ce point de terminaison.',
    'settings.api.save': 'Enregistrer l\'Intégration',
    'common.active': 'Actif',
    'common.pending': 'En attente',
    'common.blocked': 'Bloqué',
    'common.failed': 'Échoué',
    'common.success': 'Succès',
    'common.next': 'Étape suivante',
    'common.back': 'Retour',
    'common.edit': 'Modifier',
    'common.cancel': 'Annuler',
    'common.digital': 'Numérique',
    'common.physical': 'Physique',
    'common.redeemed': 'Utilisé',
    'common.expired': 'Expiré',
    'common.healthy': 'Sain',
    'common.degraded': 'Dégradé',
    'common.operator.orange': 'Orange Money',
    'common.operator.wave': 'Wave',
    'common.operator.free': 'Free Money',
    'common.operator.emoney': 'E-Money',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
